type: task
# This configuration fine-tunes Llama 2 model on Guanace dataset using QLoRA

# (Optional) When not specified, your local Python version is used
python: "3.11"

env:
  - HF_HUB_ENABLE_HF_TRANSFER=1
  # (Required) Specify your Hugging Face token to publish the fine-tuned model
  - HUGGING_FACE_HUB_TOKEN=

ports:
  - 6006

commands:
  - echo "Installing requirements..."
  - pip -q install -r llama-2/requirements.txt
  - tensorboard --logdir results/runs &
  - python llama-2/train.py --merge_and_push ${{ run.args }}
